version: '3.4'

services:
  ordersmicroservice.api:
    image: ${DOCKER_REGISTRY-}ordersmicroserviceapi
    build:
      context: .
      dockerfile: OrdersMicroservice.API/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - MONGO_HOST=localhost
     - MONGO_PORT=27017
     - MONGODB_DATABASE=OrdersDatabase
     - UsersMicroserviceName=localhost
     - UsersMicroservicePort=5050
     - ProductsMicroserviceName=localhost
     - ProductsMicroservicePort=6060
    ports:
     - "7000:8080" 
